### ISSUE TITLE
Describe what Stage 1/2/3 means in user-oriented terms

### ISSUE THREAD

**Issue by MNoya** [GetDotaStats/site#211]
Instead of Stage 1, 2, 3, would be better to display something like: **Failed to Load**, **Started** and **Ended**.

**Comment by SinZ163** [comment]
Would probably expand that stage 3 with In Progress and Ended as round based games send multiple stage 3's and specifies if its last or not

**Comment by jimmydorry** [comment]
Let's go with a set of glyphicons instead of words. I think 1 and 3 would be pretty obvious as ok and remove. What do we want as phase 2?

1,2 and 3 will be red, orange and green.

We could also just use time for all three.

Have a look at the user page. I recall using glyphicons there. The glyphicons all have a hover text.

http://getbootstrap.com/components/

**Comment by jimmydorry** [comment]
EZPZ
